services:
  orchestrator:
    build: ./orchestrator
    ports:
      - "4000:4000"
    environment:
      - JOB_URL=$JOB_URL
      - USER_URL=$USER_URL
      - PORT=4000
    volumes:
      - ./orchestrator:/orchestrator

  app:
    build: ./services/app
    ports:
      - "4002:4002"
    environment:
      - DATABASE_URL=$DATABASE_URL
      - PORT=4002

  user:
    build: ./services/users
    ports:
      - "4001:4001"
    environment:
      - PORT=4001
    volumes:
      - ./services/users:/users